abstract class AppConstants {
  static const Duration duration200 = Duration(milliseconds: 200);

  static final List<(String authorName,
  String text)> comments = [
    ('Emily Johnson', 'Nature always leaves me in awe! 🌿'),
    ('Alex Smith', 'The beauty of the world is unparalleled! 🌄'),
    ('Sarah White', 'A peaceful moment captured perfectly! 🌸'),
    ('John Davis', 'Nature truly heals the soul. 🌍'),
    ('Jessica Brown', 'Such a serene and calming view! 🏞️'),
    ('Michael Wilson', 'Feeling so connected to nature today. 🌱'),
    ('Olivia Martinez', 'These landscapes are absolutely stunning! 🌅'),
    ('Daniel Lee', 'The best part of the day is being surrounded by nature. 🌳'),
    ('Chloe Harris', 'Nature’s colors are always so vibrant! 🌼'),
    ('James Clark', 'Incredible! Mother Nature at her finest! 🌷'),
  ];

  static final List<(String name, String title)> ecologyTips = [
    ('Reduce single-use plastic consumption.', 'Use reusable bags, bottles, and containers to minimize waste.'),
    ('Recycle your waste', 'Sort your trash to ensure that paper, plastic, metal, and glass can be recycled properly'),
    ('Use energy-efficient light bulbs.', 'Energy-saving and LED bulbs consume less energy and last longer.'),
    ('Reduce water consumption.', 'Install faucets with water-saving features and fix leaky taps.'),
    ('Plant trees and plants.', 'Trees absorb carbon dioxide and provide oxygen, while indoor plants purify the air.'),
    ('Use public transport or walk.', 'Reducing the number of cars on the road helps cut down on carbon emissions.'),
    ('Reduce single-use plastic consumption.', 'Use reusable bags, bottles, and containers to minimize waste.'),
    ('Recycle your waste', 'Sort your trash to ensure that paper, plastic, metal, and glass can be recycled properly'),
  ];

  static final List<(String head, String text)> natureEvents = [
    ('Deforestation as an environmental problem',
    'Our world has always been rich in natural resources. Even now, in an era when man has learned to fully exploit nature and use it 100% for his own benefit, there are places where activity is simply impossible from the point of view of logistics and development. Therefore, in Russia there are forest areas where no man has ever set foot, and there are many such places. But, unfortunately, such places are increasingly used by unscrupulous citizens, illegally cutting down forests and selling them on the black market. The problem of illegal logging in its seriousness and danger to the environmental situation is on a par with regular logging and large forest fires, the outbreaks of which appear every summer. Forests are the lungs of the planet, a strong internal ecosystem that is integrated into our lives and is a natural environment that plays a very important role in the ecology and biosphere of our planet. Forests are important for both humans and nature as a whole for several reasons. Carbon balance - of course, we are talking about carbon dioxide and its absorption by plants and trees. This function allows us to saturate the air with oxygen and maintain its quality. Prevention of soil erosion - forests have a common root system, the roots are located in such a way that the trees do not interfere with each other\'s development and evenly receive all the necessary nutrients from the soil. Therefore, a common root system, like nothing else, protects the soil from destruction and erosion. Microclimate and biodiversity - Forests occupy a third of the land on our planet, and exist as a common ecosystem, where all the mechanisms are debugged and even have their own working personnel in the form of animals, of course, and plants. Nature is forced to adapt to human activity and under its influence, flexible mechanisms of self-renewal and recreation sometimes fail. Therefore, it is so important not to invade the natural temple, devastating everything on its way, but to rationally and carefully use its resources, necessarily restoring those parameters that a person is able to renew with his own efforts. Forests support the microclimate in which they are located and provide active support to its inhabitants, ensuring biodiversity.',
    ),
    ('Fundamentals of nature management and environmental protection',
    'Nature management and environmental protection are essential for ensuring the sustainable use of natural resources. These practices focus on balancing human needs with the preservation of ecosystems, preventing environmental degradation, and promoting responsible resource consumption. One fundamental aspect of nature management is conservation. Governments and environmental organizations establish national parks, wildlife reserves, and protected areas to safeguard biodiversity. These areas prevent industrial development, deforestation, and poaching, allowing ecosystems to thrive. Conservation efforts also include breeding programs for endangered species and the restoration of damaged habitats. Sustainable resource management is another key principle. This includes responsible forestry, where trees are replanted after logging, and sustainable fishing practices that prevent overexploitation. Agriculture also plays a role, with eco-friendly farming techniques such as crop rotation and organic farming helping to maintain soil health. Environmental protection involves policies and laws aimed at reducing pollution and minimizing ecological damage. Regulations on emissions, waste disposal, and industrial activities help keep air, water, and soil clean. Public awareness campaigns educate people about the importance of reducing plastic waste, recycling, and using renewable energy sources. Ultimately, nature management and environmental protection require cooperation between governments, businesses, and individuals. By implementing sustainable practices and respecting nature’s limits, we can preserve the planet’s resources for future generations while maintaining economic and social stability.',
    ),
    ('Ecological problems of our time',
    'The modern world faces a variety of ecological problems that threaten both the environment and human well-being. From pollution to climate change, these issues require urgent attention and action. One of the most critical problems is global warming. The burning of fossil fuels releases carbon dioxide and other greenhouse gases, trapping heat in the Earth\'s atmosphere. This leads to rising temperatures, melting ice caps, and extreme weather conditions such as hurricanes, droughts, and wildfires. Climate change also threatens agriculture, making it harder for farmers to produce food. Another major issue is plastic pollution. Every year, millions of tons of plastic waste end up in oceans, harming marine life. Birds, fish, and sea turtles often mistake plastic for food, leading to poisoning and death. Microplastics, tiny particles from broken-down plastic, have even been found in drinking water and food, raising health concerns for humans. Deforestation continues to be a serious problem, destroying habitats and contributing to biodiversity loss. Without forests, many species struggle to survive, and the planet loses its ability to absorb carbon dioxide effectively. In addition, air and water pollution from factories, vehicles, and industrial waste negatively impact human health, leading to respiratory diseases and contaminated drinking water sources. To address these issues, governments must implement stricter environmental regulations, and individuals should adopt sustainable habits such as reducing plastic use, supporting clean energy, and conserving water. Only through collective efforts can we hope to solve the ecological crises of our time.'
    ),
    ('The Fragile Balance of Earth\'s Ecosystems',
    'The Earth\'s ecosystems are complex and delicately balanced systems that support life in all its diversity. From vast rainforests to the deepest oceans, every environment plays a crucial role in maintaining the planet\'s overall health. However, human activities have increasingly disrupted this balance, leading to serious environmental consequences. One of the most critical aspects of ecosystems is biodiversity. Each species, from the smallest insect to the largest predator, contributes to the stability of its habitat. Plants produce oxygen, animals control populations, and microorganisms break down organic matter, creating a cycle that keeps nature in harmony. When even a single species is removed or declines drastically, it can have a domino effect on the entire ecosystem. Deforestation is one of the greatest threats to ecosystems worldwide. Forests act as natural carbon sinks, absorbing carbon dioxide and helping regulate the planet’s temperature. However, logging, agriculture, and urban expansion have led to massive forest loss, contributing to climate change and the destruction of habitats. As forests disappear, countless species lose their homes, leading to biodiversity loss at an alarming rate. Another pressing issue is pollution, which affects land, air, and water ecosystems. Industrial waste, plastic pollution, and chemical runoff disrupt natural cycles, often causing long-term damage. Oceans, which cover more than 70% of the Earth’s surface, suffer greatly from pollution. Plastic waste harms marine life, oil spills contaminate habitats, and rising temperatures cause coral bleaching. Without intervention, these changes could lead to irreversible damage to marine ecosystems. Climate change also plays a significant role in ecosystem disruption. Rising global temperatures alter weather patterns, causing extreme droughts, hurricanes, and wildfires. Polar ice caps are melting, leading to rising sea levels and the loss of habitats for species such as polar bears and penguins. As ecosystems struggle to adapt to these rapid changes, many species face extinction, further destabilizing the environment. Despite these challenges, there is hope. Conservation efforts, reforestation projects, and sustainable practices can help restore balance to ecosystems. Protected areas, such as national parks and marine reserves, provide safe havens for wildlife. Reducing pollution, cutting carbon emissions, and supporting biodiversity-friendly policies can also make a difference. Individuals can contribute by making eco-friendly choices, such as reducing plastic use, supporting sustainable products, and participating in conservation programs. The fragile balance of Earth\'s ecosystems is essential for all life on the planet. If humanity works together to protect and restore these natural systems, future generations can continue to benefit from the beauty and resources that nature provides.'
    ),
  ];
}